package com.jbk.entity;
// Generated Aug 13, 2020 6:15:53 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "sachin")
public class Course implements java.io.Serializable {

	private Integer courseId;
	private String courseName;
	//private Set<Student> students = new HashSet<Student>(0);

	public Course() {
	}

	public Course(String courseName) {
		this.courseName = courseName;
	}

	/*
	 * public Course(String courseName, Set<Student> students) { this.courseName =
	 * courseName; this.students = students; }
	 */

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "course_id", unique = true, nullable = false)
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "course_name", nullable = false, length = 45)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "course") public Set<Student>
	 * getStudents() { return this.students; }
	 * 
	 * public void setStudents(Set<Student> students) { this.students = students; }
	 */
}
