package com.jbk.entity;
// Generated Aug 13, 2020 6:15:53 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "sachin")
public class Student implements java.io.Serializable {

	private Integer studId;
	private Course course;
	private String studName;
	private String studAddress;
	private String studContact;
	private String studEmail;

	public Student() {
	}

	public Student(Course course, String studName, String studAddress, String studContact, String studEmail) {
		this.course = course;
		this.studName = studName;
		this.studAddress = studAddress;
		this.studContact = studContact;
		this.studEmail = studEmail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stud_id", unique = true, nullable = false)
	public Integer getStudId() {
		return this.studId;
	}

	public void setStudId(Integer studId) {
		this.studId = studId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "stud_name", nullable = false, length = 45)
	public String getStudName() {
		return this.studName;
	}

	public void setStudName(String studName) {
		this.studName = studName;
	}

	@Column(name = "stud_address", nullable = false, length = 45)
	public String getStudAddress() {
		return this.studAddress;
	}

	public void setStudAddress(String studAddress) {
		this.studAddress = studAddress;
	}

	@Column(name = "stud_contact", nullable = false, length = 45)
	public String getStudContact() {
		return this.studContact;
	}

	public void setStudContact(String studContact) {
		this.studContact = studContact;
	}

	@Column(name = "stud_email", nullable = false, length = 45)
	public String getStudEmail() {
		return this.studEmail;
	}

	public void setStudEmail(String studEmail) {
		this.studEmail = studEmail;
	}

}
